# .gitpod.yml
image:
  file: .gitpod.Dockerfile

tasks:
  - init: docker pull jlesage/firefox:latest
  - command: |
      docker run -d \
        --name=firefox \
        -p 5800:5800 \
        -v /docker/appdata/firefox:/config:rw \
        jlesage/firefox:latest
